// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx81XRP7dj6KkeggGcVV0cj_-8tPkrWSU',
    appId: '1:833990495862:web:5a429de9a1aa9eb712d957',
    messagingSenderId: '833990495862',
    projectId: 'task-organizer-8cff2',
    authDomain: 'task-organizer-8cff2.firebaseapp.com',
    storageBucket: 'task-organizer-8cff2.firebasestorage.app',
    measurementId: 'G-BCYL6GXV9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30aYEKIhYgZ3XgsRZfHSr4qMxvdNlKis',
    appId: '1:833990495862:android:483daaa5b7f2bade12d957',
    messagingSenderId: '833990495862',
    projectId: 'task-organizer-8cff2',
    storageBucket: 'task-organizer-8cff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeEtZStgz_hfz2jMVeLhXVPNePIjd86x8',
    appId: '1:833990495862:ios:7d7ba1060144520012d957',
    messagingSenderId: '833990495862',
    projectId: 'task-organizer-8cff2',
    storageBucket: 'task-organizer-8cff2.firebasestorage.app',
    iosBundleId: 'com.example.taskOrganizaer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeEtZStgz_hfz2jMVeLhXVPNePIjd86x8',
    appId: '1:833990495862:ios:7d7ba1060144520012d957',
    messagingSenderId: '833990495862',
    projectId: 'task-organizer-8cff2',
    storageBucket: 'task-organizer-8cff2.firebasestorage.app',
    iosBundleId: 'com.example.taskOrganizaer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx81XRP7dj6KkeggGcVV0cj_-8tPkrWSU',
    appId: '1:833990495862:web:4f99dbaf0930e4df12d957',
    messagingSenderId: '833990495862',
    projectId: 'task-organizer-8cff2',
    authDomain: 'task-organizer-8cff2.firebaseapp.com',
    storageBucket: 'task-organizer-8cff2.firebasestorage.app',
    measurementId: 'G-4HRYKXKGMZ',
  );
}
